# Generated by Django 2.0.6 on 2018-06-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '01_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
